steps:
  # This step install mvn packages
  - name: 'gcr.io/cloud-builders/mvn'
    id: Install
    args: ['clean','install']
  # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/dev1-onb-playground-18fd/recommendation:latest'
      - '.'

  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/dev1-onb-playground-18fd/recommendation:latest'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Create deployment
    args:
      - 'apply'
      - '-f'
      - 'kubernetes.yml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=app'
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Fetch changes
    args:
      - 'rollout'
      - 'restart'
      - 'deployment/recommendation'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=app'